import { motion } from 'motion/react';
import { gsap } from 'gsap';
import { useRef, useEffect } from 'react';
import { BookOpen, Brain, ArrowLeft } from 'lucide-react';

interface QuizModeSelectionProps {
  topicName: string;
  onSelectMode: (mode: 'regular' | 'ai') => void;
  onBack: () => void;
}

const modes = [
  {
    type: 'regular' as const,
    title: 'Regular Quiz',
    description: 'Pre-made questions with instant feedback',
    icon: BookOpen,
    color: 'from-blue-500 to-cyan-500',
    borderColor: 'border-blue-400/30',
    hoverBorder: 'hover:border-blue-400',
    textColor: 'text-blue-400',
    features: [
      'Fixed question bank',
      'Instant answers',
      'Timed challenges',
      'Leaderboard tracking'
    ]
  },
  {
    type: 'ai' as const,
    title: 'AI-Powered Quiz',
    description: 'Dynamic questions generated by Ollama AI',
    icon: Brain,
    color: 'from-purple-500 to-pink-500',
    borderColor: 'border-purple-400/30',
    hoverBorder: 'hover:border-purple-400',
    textColor: 'text-purple-400',
    features: [
      'AI-generated questions',
      'Smart evaluation',
      'Unique every time',
      'Detailed feedback'
    ],
    badge: 'AI'
  },
];

export const QuizModeSelection = ({
  topicName,
  onSelectMode,
  onBack
}: QuizModeSelectionProps) => {
  const cardRefs = useRef<(HTMLDivElement | null)[]>([]);

  useEffect(() => {
    cardRefs.current.forEach((card, index) => {
      if (card) {
        gsap.from(card, {
          opacity: 0,
          y: 50,
          scale: 0.8,
          duration: 0.6,
          delay: index * 0.2,
          ease: 'back.out(1.7)',
        });
      }
    });
  }, []);

  const handleCardMouseMove = (e: React.MouseEvent<HTMLDivElement>, index: number) => {
    const card = cardRefs.current[index];
    if (!card) return;

    const rect = card.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const centerX = rect.width / 2;
    const centerY = rect.height / 2;

    const rotateX = ((y - centerY) / centerY) * -10;
    const rotateY = ((x - centerX) / centerX) * 10;

    gsap.to(card, {
      rotateX,
      rotateY,
      duration: 0.3,
      ease: 'power2.out',
      transformPerspective: 1000,
    });
  };

  const handleCardMouseLeave = (index: number) => {
    const card = cardRefs.current[index];
    if (!card) return;

    gsap.to(card, {
      rotateX: 0,
      rotateY: 0,
      duration: 0.5,
      ease: 'power2.out',
    });
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-8 relative">
      {/* Back button */}
      <motion.button
        onClick={onBack}
        className="absolute top-8 left-8 flex items-center gap-2 px-6 py-3 bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl text-white hover:bg-white/10 hover:border-cyan-400/30 transition-all duration-300 z-20"
        initial={{ opacity: 0, x: -50 }}
        animate={{ opacity: 1, x: 0 }}
        whileHover={{ scale: 1.05, x: -5 }}
        whileTap={{ scale: 0.95 }}
      >
        <ArrowLeft className="w-5 h-5" />
        Back
      </motion.button>

      <div className="max-w-6xl mx-auto w-full">
        {/* Title */}
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0, y: -30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="text-5xl font-black text-white mb-4">
            Choose Quiz Mode
          </h1>
          <p className="text-xl text-white/60">
            Topic: <span className="text-cyan-400 font-semibold">{topicName}</span>
          </p>
        </motion.div>

        {/* Mode cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-5xl mx-auto">
          {modes.map((mode, index) => {
            const Icon = mode.icon;
            return (
              <motion.div
                key={mode.type}
                ref={(el) => (cardRefs.current[index] = el)}
                className="relative group cursor-pointer"
                style={{ perspective: 1000 }}
                onMouseMove={(e) => handleCardMouseMove(e, index)}
                onMouseLeave={() => handleCardMouseLeave(index)}
                onClick={() => onSelectMode(mode.type)}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                {/* Card glow */}
                <div className={`absolute -inset-1 bg-gradient-to-r ${mode.color} rounded-3xl blur-xl opacity-0 group-hover:opacity-70 transition-opacity duration-500`} />

                {/* Card content */}
                <div className={`relative bg-white/5 backdrop-blur-xl border ${mode.borderColor} ${mode.hoverBorder} rounded-3xl p-8 h-[450px] flex flex-col transition-all duration-300 group-hover:bg-white/10`}>
                  {/* Badge */}
                  {mode.badge && (
                    <div className="absolute top-4 right-4">
                      <div className={`px-3 py-1 bg-gradient-to-r ${mode.color} rounded-full text-white text-xs font-bold`}>
                        {mode.badge}
                      </div>
                    </div>
                  )}

                  {/* Icon with animation */}
                  <motion.div
                    className={`mb-6 ${mode.textColor}`}
                    whileHover={{
                      rotate: [0, -10, 10, -10, 0],
                      scale: [1, 1.2, 1.2, 1.2, 1]
                    }}
                    transition={{ duration: 0.5 }}
                  >
                    <Icon className="w-20 h-20" strokeWidth={1.5} />
                  </motion.div>

                  {/* Title */}
                  <h3 className={`text-3xl font-black ${mode.textColor} mb-3`}>
                    {mode.title}
                  </h3>

                  {/* Description */}
                  <p className="text-white/60 text-center text-sm mb-6">
                    {mode.description}
                  </p>

                  {/* Features */}
                  <div className="flex-1 space-y-3">
                    {mode.features.map((feature, idx) => (
                      <motion.div
                        key={idx}
                        className="flex items-center gap-2"
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.1 * idx }}
                      >
                        <div className={`w-2 h-2 rounded-full bg-gradient-to-r ${mode.color}`} />
                        <p className="text-white/80 text-sm">{feature}</p>
                      </motion.div>
                    ))}
                  </div>

                  {/* Hover button */}
                  <motion.div
                    className="mt-6 opacity-0 group-hover:opacity-100 transition-opacity duration-300"
                    initial={{ y: 10 }}
                    whileHover={{ y: 0 }}
                  >
                    <div className={`w-full py-3 bg-gradient-to-r ${mode.color} rounded-xl text-white font-bold text-center shadow-lg`}>
                      Start {mode.title}
                    </div>
                  </motion.div>
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Info text for AI mode */}
        <motion.div
          className="text-center mt-12 max-w-2xl mx-auto"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8, duration: 1 }}
        >
          <div className="bg-purple-500/10 border border-purple-500/30 rounded-xl p-4">
            <p className="text-purple-400 text-sm mb-2">
              <Brain className="w-4 h-4 inline mr-2" />
              AI Mode Requirements
            </p>
            <p className="text-white/60 text-xs">
              TEAM
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
};
